[package]
name = "rustdecrypt"
version = "0.1.0"
authors = ["samuel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
positioned-io = "0.2"
structure = "0.1.2"
